### ISSUE TITLE
1.17 update in CDN but not in search

### ISSUE THREAD

**Issue by pertsevds** [version-fox/vfox-elixir#9]
1.17.1 and 1.17.0 is in
https://fastly.jsdelivr.net/gh/version-fox/vfox-elixir@main/assets/versions.txt
right now
```shell
curl https://fastly.jsdelivr.net/gh/version-fox/vfox-elixir@main/assets/versions.txt | grep 1.17
1.17.1
1.17.0
1.17.0-rc.1
1.17.0-rc.0
```
but when I clean cache and try to install 1.17.1
```shell
rm ~/.version-fox/plugin/elixir/available.cache
vfox search elixir
```
It only prints v1.17.0-rc.1 and v1.17.0-rc.0.

MacOS 14.5, vfox 0.5.3

Are there any other cache or am I missing something?

**Comment by yeshan333** [comment]
I can not reproduce this problem.

![image](https://github.com/version-fox/vfox-elixir/assets/39296814/5442e14b-dd0b-413e-85a6-ed2a8a36dad0)

version.txt was automatically updated 13 hours ago in this commit：https://github.com/version-fox/vfox-elixir/commit/9f13845f1bcfc34ec4f930634cb6c85e5bb7abe5#diff-28a66ebb5faf4f27eb38150c6db0ad99d92e84f53a9137e6037cef9fa7b99b6f

when I delete the vfox cache `rm ~/.version-fox/plugin/elixir/available.cache`. I can normally found the v.17.0 & v1.17.1 version of Elixir.

**Comment by yeshan333** [comment]
If you cannot find the version you want to install using `vfox search`, the plug-in implementation also supports installing any version that appears in the https://github.com/elixir-lang/elixir/releases page.

**Comment by pertsevds** [comment]
Now it's fixed. It's in the search.

> version.txt was automatically updated at 13 hours ago

In HTTP headers from 
https://fastly.jsdelivr.net/gh/version-fox/vfox-elixir@main/assets/versions.txt
```
Cache-Control: public, max-age=604800, s-maxage=43200
```
s-maxage = 12 hours. That may be the reason.
12 hours passed and CDN cache refreshed.

**Comment by pertsevds** [comment]
I'll close the issue for now.
